spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.k3w02.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      port: 27017
      host: localhost
      database: springboot
      username: admin
      password: admin
